# Logistic regression

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("/Users/sunny/Downloads/Telegram Desktop/bank.csv")

In [3]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [6]:
x=dataset.iloc[:,0:16].values

In [7]:
y=dataset.iloc[:,16].values

In [8]:
x.shape

(11162, 16)

In [9]:
y.shape

(11162,)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)

In [11]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [12]:
x.shape

(11162, 51)

In [13]:
y

array(['yes', 'yes', 'yes', ..., 'no', 'no', 'no'], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [15]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [17]:
x_train

array([[0.0, 1.0, 0.0, ..., 1, -1, 0],
       [0.0, 1.0, 0.0, ..., 10, -1, 0],
       [0.0, 1.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 2, 391, 11],
       [0.0, 1.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [18]:
x_test

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 1.0, 0.0, ..., 2, -1, 0],
       [0.0, 1.0, 0.0, ..., 2, -1, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 3, -1, 0],
       [0.0, 0.0, 0.0, ..., 4, -1, 0]], dtype=object)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc=StandardScaler()

In [21]:
x_train=sc.fit_transform(x_train)
x_train

array([[-0.36918047,  2.17933868, -0.17145904, ..., -0.55002237,
        -0.48107659, -0.3612238 ],
       [-0.36918047,  2.17933868, -0.17145904, ...,  2.73405131,
        -0.48107659, -0.3612238 ],
       [-0.36918047,  2.17933868, -0.17145904, ..., -0.55002237,
        -0.48107659, -0.3612238 ],
       ...,
       [-0.36918047, -0.45885479,  5.83229683, ..., -0.55002237,
        -0.48107659, -0.3612238 ],
       [ 2.7087023 , -0.45885479, -0.17145904, ..., -0.18512529,
         3.11825242,  4.40298199],
       [-0.36918047,  2.17933868, -0.17145904, ..., -0.55002237,
        -0.48107659, -0.3612238 ]])

In [22]:
x_test=sc.fit_transform(x_test)
x_test

array([[ 2.73687674, -0.4607269 , -0.18383769, ..., -0.57160825,
        -0.48162849, -0.37193034],
       [-0.36537999,  2.17048323, -0.18383769, ..., -0.19375117,
        -0.48162849, -0.37193034],
       [-0.36537999,  2.17048323, -0.18383769, ..., -0.19375117,
        -0.48162849, -0.37193034],
       ...,
       [-0.36537999, -0.4607269 ,  5.43958097, ..., -0.57160825,
        -0.48162849, -0.37193034],
       [-0.36537999, -0.4607269 , -0.18383769, ...,  0.18410591,
        -0.48162849, -0.37193034],
       [-0.36537999, -0.4607269 , -0.18383769, ...,  0.561963  ,
        -0.48162849, -0.37193034]])

In [23]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)

LogisticRegression()

In [24]:
ypred=logreg.predict(x_test)

In [25]:
ypred

array([0, 0, 0, ..., 1, 1, 0])

In [26]:
y_test

array([0, 0, 0, ..., 1, 1, 0])

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
accuracy=accuracy_score(ypred,y_test)

In [29]:
accuracy

0.8213166144200627

In [30]:
logreg.predict(ct.transform([[41,"technician","married","secondary","no",1270,"yes","no","unknown",5,"may",1389,1,-1,0,"unknown"]]))

array([1])

In [ ]:
#so the person will deposit in bank